[WIP] Feature/rewrite
shiguredo/kohaku-legacy pull request #69
Opened 2023-04-13 09:35 UTC by voluntas

2023-05-10 08:13 UTC, Hexa requested changes

2023-05-10 08:13 UTC, Hexa commented on db/query.sql
> +    ) as old_data,
```
SELECT existing_record.rtc_stats_data - 'timestamp' as old_data,
```

timestap キーを削除する場合は、- 'timestamp' でよさそうです

https://www.postgresql.jp/document/14/html/functions-json.html

2023-05-10 08:13 UTC, Hexa commented on db/query.sql
> +    ) as new_data
こちらも timestamp を削除する場合は - 'timestamp' で簡単に書けると思います

2023-05-10 08:13 UTC, Hexa commented on server.go
> +		Addr:    net.JoinHostPort("", strconv.Itoa(s.config.ListenPort)),
host は s.config.ListenAddr を指定するか、または、指定する前に下記で確認するとよさそうです

```
	_, err := netip.ParseAddr(s.config.ListenPort)
	if err != nil {
		return err
	}
```

2023-05-10 08:13 UTC, voluntas commented on db/query.sql
> +    ) as old_data,
えぇぇ、そんな文法あんの ... 。テスト書いてあるから、修正してしまってください。

2023-05-10 08:14 UTC, voluntas commented on server.go
> +		Addr:    net.JoinHostPort("", strconv.Itoa(s.config.ListenPort)),
👍 修正しちゃってください

2023-05-10 08:15 UTC, Hexa commented on db/query.sql
> +    ) as old_data,
はい

2023-05-11 04:17 UTC, Hexa commented on db/query.sql
> +    ) as old_data,
https://github.com/shiguredo/kohaku/commit/5dc63eff3be7a2d6dfbea479154ea6ba9e376bda

上記で対応しました

2023-05-11 04:19 UTC, Hexa commented on db/query.sql
> +    ) as new_data
https://github.com/shiguredo/kohaku/commit/5dc63eff3be7a2d6dfbea479154ea6ba9e376bda

 @ の場合は sqlc generate でエラーになったため、その旨をコメントに残して変更なしにしました

2023-05-11 04:20 UTC, Hexa commented on server.go
> +		Addr:    net.JoinHostPort("", strconv.Itoa(s.config.ListenPort)),
https://github.com/shiguredo/kohaku/commit/f14a1c9d2dead8080d435f14815eecefdfe24e1e

対応しました

2023-05-11 07:56 UTC, merged